PIPELINE:
  TRIMMING:
    PRETRAINED_MODEL: "model_final.pkl"
    CONFIGURATION: "e2e_mask_rcnn_X_101_32x8d_FPN_1x.yaml"
  TRAINING:
    NGPUS: 4
  ARTIFICIAL_PATCH_GENERATOR:
    NUM_PATCHES: 200
    NUM_THROWS: 1000
    NUM_ANGLES: 60
    RATIO: 0.8
    PATCH_SIZE: (400,400)
  INFERENCE:
    CONFIGURATION: "inferenceConfigX101.yaml"
    SUBIMAGE_SIZE: (400,400)
  WAFER_MERGE:
    AREA_THRESHOLD: 0.4
    MIN_DISTANCE_THRESHOLD: 0.5

